// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEkmf4x_NCySDC5VQuKzLFlrPz8tHApKc',
    appId: '1:871605088868:web:9ae1b89da20f8d3729e571',
    messagingSenderId: '871605088868',
    projectId: 'daily-reset-cheese',
    authDomain: 'daily-reset-cheese.firebaseapp.com',
    storageBucket: 'daily-reset-cheese.firebasestorage.app',
    measurementId: 'G-NJW4W5DGD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_qQuuqR3z70VaqNmBKhKi3oHOZZxh0F8',
    appId: '1:871605088868:android:1e55bd84408402df29e571',
    messagingSenderId: '871605088868',
    projectId: 'daily-reset-cheese',
    storageBucket: 'daily-reset-cheese.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9OnN0i4tfVRO9HDG4j-Vq2VubCLMxGmk',
    appId: '1:871605088868:ios:fac990ec3010496f29e571',
    messagingSenderId: '871605088868',
    projectId: 'daily-reset-cheese',
    storageBucket: 'daily-reset-cheese.firebasestorage.app',
    iosBundleId: 'com.example.dailyReset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9OnN0i4tfVRO9HDG4j-Vq2VubCLMxGmk',
    appId: '1:871605088868:ios:fac990ec3010496f29e571',
    messagingSenderId: '871605088868',
    projectId: 'daily-reset-cheese',
    storageBucket: 'daily-reset-cheese.firebasestorage.app',
    iosBundleId: 'com.example.dailyReset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEkmf4x_NCySDC5VQuKzLFlrPz8tHApKc',
    appId: '1:871605088868:web:8b15635df8e569e629e571',
    messagingSenderId: '871605088868',
    projectId: 'daily-reset-cheese',
    authDomain: 'daily-reset-cheese.firebaseapp.com',
    storageBucket: 'daily-reset-cheese.firebasestorage.app',
    measurementId: 'G-1FVSSS06C7',
  );
}
